name: Build aria2

on:
  push:
  workflow_dispatch:

jobs:
  build:
    env:
      PROJECT_REPOSITORY: zeromake/aria2-zero
      PROJECT_VERSION: None
      PROJECT_PATH: aria2
      PROJECT_BIN: aria2
    runs-on: windows-2022
    steps:
      - name: config git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      
      - name: switch ${{ env.PROJECT_PATH }}
        uses: actions/checkout@v6
        with:
          repository: ${{ env.PROJECT_REPOSITORY }}
          path: .
          submodules: 'recursive'
      
      - name: xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      
      - name: Build
        env:
          VERSION: ""
        run: |
          xmake f -a x64 -m minsizerel --runtimes=MD `
            --policies=build.optimization.smallest `
            --cxxflags=" /fp:fast /Gy /GL /Gw /MD /MP /Oi /Os /GR- /GS-" `
            --ldflags=" /LTCG /OPT:REF /OPT:ICF /MERGE:_RDATA=.rdata" `
            -c -y

      - uses: actions/upload-artifact@v5
        with:
          name: aria2c_${{ github.run_id }}
          path: |
            build/windows/x64/release/aria2c.exe
