name: Build rufus

on:
  push:
  workflow_dispatch:

jobs:
  build:
    env:
      PROJECT_REPOSITORY: ProjectMile/Mile.Aria2
      PROJECT_VERSION: 1.0.1050.0
      PROJECT_PATH: Aria2
      PROJECT_BIN: Aria2
    strategy:
      matrix:
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: switch ${{ env.PROJECT_PATH }}
        uses: actions/checkout@v6
        with:
          repository: ${{ env.PROJECT_REPOSITORY }}
          path: ${{ env.PROJECT_PATH }}
          submodules: 'recursive'

      - name: setup msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet nuget locals all --clear
      
      - name: Build
        working-directory: ${{ env.PROJECT_PATH }}
        run: msbuild BuildAllTargets.proj /t:Build /p:Configuration=Release /p:Platform=x64 /m
      
      - name: Prepare artifacts
        working-directory: ${{ env.PROJECT_PATH }}
        run: rm Output\Binaries\* -vb -Recurse -Force -Include *.exp, *.idb, *.ilk, *.iobj, *.ipdb, *.lastbuildstate, *.lib, *.obj, *.res, *.tlog
      
      - uses: actions/upload-artifact@v5
        with:
          name: Mile.Aria2_CI_Build
          path: ${{ env.PROJECT_PATH }}\Output\Binaries
